name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  json:
    description: "The JSON to convert to CSV"
    required: true
  options:
    description: "A JSON string of options https://www.npmjs.com/package/json-2-csv#json2csvarray-options--string"
    required: false

outputs:
  csv:
    description: "A CSV string"

runs:
  using: "node20"
  main: "dist/index.js"
