name: JSON to CSV Action
author: Austen Stone
description: Convert JSON to CSV format
branding:
  icon: "align-justify"
  color: "blue"

inputs:
  json:
    description: "The JSON to convert to CSV"
    required: false
  json-artifact-name:
    description: "The name of the JSON artifact to convert to CSV"
    required: false
  options:
    description: "A JSON string of options https://www.npmjs.com/package/json-2-csv#json2csvarray-options--string"
    required: false
  create-artifact:
    description: Whether to create an artifact with the alerts
    required: false
    default: true
  artifact-name:
    description: The name of the artifact to create
    required: false
    default: ${{ github.workflow }}

outputs:
  csv:
    description: "A CSV string"
  artifact-name:
    description: "The name of the artifact created"

runs:
  using: "node20"
  main: "dist/index.js"
