name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: csv
        with:
          json: '[{"name": "test"}, {"name": "test2"}]'
      - run: echo "${{ steps.csv.outputs.csv }}"